# Generated by Django 4.2.4 on 2023-08-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0002_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_me',
            field=models.BooleanField(default=False),
        ),
    ]
