# Generated by Django 4.2.4 on 2023-08-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0003_userprofile_contact_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_be_contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_data_be_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='zagablai', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
