# Generated by Django 4.2.4 on 2023-08-20 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0005_remove_userprofile_contact_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
