# Generated by Django 4.2.4 on 2023-08-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0006_contributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_be_contacted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_data_be_shared',
            field=models.BooleanField(default=True),
        ),
    ]
