# Generated by Django 4.2.4 on 2023-08-20 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserProfile_API', '0006_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=2048)),
                ('priority', models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')], max_length=1)),
                ('type', models.IntegerField(choices=[(1, 'BUG'), (2, 'FEATURE'), (3, 'TASK')], max_length=1)),
                ('progression', models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Finished')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_API.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support_API.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=2048)),
                ('Issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support_API.issue')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_API.contributor')),
            ],
        ),
    ]
