# Generated by Django 4.2.4 on 2023-08-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'LOW'), (2, 'MEDIUM'), (3, 'HIGH')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='progression',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Finished')]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.IntegerField(choices=[(1, 'BUG'), (2, 'FEATURE'), (3, 'TASK')]),
        ),
    ]
