# Generated by Django 4.2.4 on 2023-08-20 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0006_contributor'),
        ('Support_API', '0002_alter_issue_priority_alter_issue_progression_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_author', models.BooleanField(default=False)),
                ('contributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile_API.contributor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Support_API.project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(through='Support_API.ContributorProjet', to='UserProfile_API.contributor'),
        ),
    ]
