# Generated by Django 4.2.4 on 2023-08-20 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile_API', '0007_alter_userprofile_can_be_contacted_and_more'),
        ('Support_API', '0004_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributorprojet',
            name='is_author',
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_authored', to='UserProfile_API.contributor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='projects_contributed', through='Support_API.ContributorProjet', to='UserProfile_API.contributor'),
        ),
    ]
