# Generated by Django 4.2.4 on 2023-08-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Support_API', '0005_remove_contributorprojet_is_author_project_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='type',
            new_name='issue_type',
        ),
    ]
