# Generated by Django 4.2.4 on 2023-08-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Support_API', '0007_alter_issue_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Issue',
            new_name='issue',
        ),
    ]
