# Generated by Django 4.2.4 on 2023-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Support_API', '0014_rename_comment_uuid_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
